require:
  - rubocop-rails
  
Rails:
  Enabled: true

    # 文字数上限
LineLength:
  Max: 130

AllCops:
  TargetRubyVersion: 2.6.3
  TargetRailsVersion: 6.1.3.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
