version: 2.1
jobs:
  build:
    docker:
      -image: circleci/ruby
      environment:
        -BUNDLRE_VERSION:2.0.2
        -RAILS_ENV: "yumyum_test"
      -image: circleci/mysql:8.0.25
        environment:
          MYSQL_ROOT_PASSWORD: password

working_directory: ~/yumyum

steps:
  - checkout
  -restore_cache:
    keys:
      -v1-dependencies-{{ checksum "Gemfile.lock" }}
      - v1-dependencies-

  -run:
    name: install dependencies
    command: |
      gem install bundler -v 2.0.2
      bundle install --jobs=4 --retry=3 --path vendor/bundle

  - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

   - run: mv config/database.yml.ci config/database.yml

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

  -run:
    name: rubocop
    command: bundle exec rubocop

  - run:
      name: Run rspec
      command: bundle exec rspec
